name: SQL Tests

on:
  push:
    branches:
      - "main"
    paths:
      - "**.sql"

permissions:
  contents: read

jobs:
  setup_mysql:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Run Tests
        run: |
          sudo systemctl start mysql
          GREEN='\033[0;32m'
          NC='\033[0m'
          echo -e "${GREEN}[+] Running SQL Tests...${NC}"
          sudo mysql -u root -proot < src/sql/create_db.sql
          sudo mysql -u root -proot < src/sql/example_inserts.sql
          sudo systemctl stop mysql
