name: SQL Tests

on:
  push:
    branches:
      - "main"
    paths:
      - "**.sql"

permissions:
  contents: read

jobs:
  setup_mysql:
    runs-on: ubuntu-latest
    steps:
      - name: Setup MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql database: 'SuperTrackerDB'
          mysql user: 'developer'
          mysql password: ${{ secrets.DB_PASS }}
      - name: Run tests
        run: |
          ls -al
          sudo mysql -u root < src/sql/create_db.sql
