name: SQL Tests

on: [ push ]
#   push:
#     branches:
#       - "main"
#     paths:
#       - "**.sql"

permissions:
  contents: read

jobs:
  setup_mysql:
    runs-on: ubuntu-latest
    steps:
      - name: Setup MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql database: 'SuperTrackerDB'
          mysql user: 'developer'
          mysql password: ${{ secrets.DB_PASS }}
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Run Tests
        run: |
          sudo systemctl start mysql
          GREEN='\033[0;32m'
          NC='\033[0m'
          echo -e "${GREEN}[+] Running SQL Tests...${NC}"
          sudo mysql -u root -p${{ secrets.DB_PASS }} < src/sql/create_db.sql
