name: Safety Scan

on:
  push:
    branches:
      - "main"
    paths:
      - "Pipfile.lock"

jobs:
  safety_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.14
      - name: Install pipenv
        run: pip install pipenv
      - name: Run tests
        run: |
          pipenv install --dev
          pipenv check -v
