name: Safety Scan

on:
  push:
    branches:
      - "main"
    paths:
      - "Pipfile.lock"

permissions:
  contents: read

jobs:
  Safety-Scan:
    runs-on: ubuntu-latest
    steps:
        - uses: pyupio/safety-action@v1
          with:
            api-key: ${{ secrets.SAFETY_API_KEY }}
